spring:
  application:
    name: My Application

  datasource:
    url: jdbc:h2:C:/Data;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
      format-sql: true
    show-sql: true


logging:
  level:
    org.hibernate.SQL: debug


server:
  port: 9000

